### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Zt-freak** [ZT2Indonesia/Animal-Light-Fix-Patch-Zoo-Tycoon-2#1]
Where is the source code in the repo? It's just a markdown file now.

**Comment by ZT2Indonesia** [comment]
Yes i know do you game Improved animal patch it's a fixed update From Reddit web? https://www.reddit.com/r/ZooTycoon/comments/sxklgt/animal_light_fix_patch_zoo_tycoon_2_mod_2022/?utm_source=share&utm_medium=web2x&context=3

**Comment by ZT2Indonesia** [comment]
> Where is the source code in the repo? It's just a markdown file now.

Ok

**Comment by ZT2Indonesia** [comment]
> That is not an answer to my question.

it's okay Maybe Zt Freak
